### ISSUE TITLE
BatchScriptExecutor Execute does not maintain state during directory changes

### ISSUE THREAD

**Issue by SloppyJaconda** [joaope/LocalAppVeyor#14]
When testing the LocalAppVeyor using TinyFormat's appveyor file I noticed that cmake was never generating any of the files due to directory traversal

During the build_script block (below for reference), when it creates and moves to the new directory the directory change does not persist to the next step. This is because `BatchScriptExecuter.Execute` launches a new cmd window for each step, which causes the directory change to be lost.

```  
build_script:
  - echo --------------------------------------------------------------------------------
  - echo Build tinyformat
  - mkdir build
  - cd build 
  - cmake -G "%COMPILER%" .. 
  - cmake --build . --config %CONFIGURATION%
```

**Comment by SloppyJaconda** [comment]
I have a quick and dirty work around. 
Rather than executing immediately, generate a bat or ps1 with the steps. Execute the file generated at the end of ScriptBlockExecuterStep. Execute or when switching between batch and powershell, discard the file after execution to prevent multiple execution.

**Comment by joaope** [comment]
This is by design. Each line is, effectively, it's own script. This is true for both localappveyor and appveyor itself.

To achieve what you want you've to make the line a [block](https://stackoverflow.com/a/39408964/87825). This is _YAML_ sintax and there are [multiple subtle different ways of represent blocks](https://stackoverflow.com/a/21699210/87825).

Your example would be:

```yaml
build_script:
  - |-
    echo --------------------------------------------------------------------------------
    echo Build tinyformat
    mkdir build
    cd build 
    cmake -G "%COMPILER%" .. 
    cmake --build . --config %CONFIGURATION%
```

If you look at [appveyor.yml](https://www.appveyor.com/docs/appveyor-yml/) reference, you can see that you can even mix both batch and powershell scripts for example. Just because the lines are contiguous it doesn't mean they run within the same context.

```yaml
install:
  # by default, all script lines are interpreted as batch
  - echo This is batch
  # to run script as a PowerShell command prepend it with ps:
  - ps: Write-Host 'This is PowerShell'
  # batch commands start from cmd:
  - cmd: echo This is batch again
  - cmd: set MY_VAR=12345
```
