### ISSUE TITLE
Support `assembly_info` step

### ISSUE THREAD

**Issue by joaope** [joaope/LocalAppVeyor#3]
Format:

```
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "2.2.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
```

Should support patching of both _AssemblyInfo.cs_ and _AssemblyInfo.vb_ files.
